config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'pages#home'
  devise_for :users
  get :search, to: "search#index"
 
  resources :contact_forms, only: [:create]
 
  resources :portfolios, except: :new do
    resources :tags, only: [:create, :destroy], param: :tag_id, controller: :portfolio_tags
    resources :blocks, only: [:index, :create, :destroy] do
      resources :additional_informations, only: [:index, :update]
      patch :positions, on: :collection, to: "block_positions#update"
    end
    resources :profiles, only: [:index, :update]
    resources :experiences, only: [:index, :create, :destroy]
    resources :educations, only: [:index, :create, :destroy]
    resources :skills, only: [:index, :create, :destroy]
    resources :hobbies, only: [:index, :create, :destroy]
    resources :languages, only: [:index, :create, :destroy]
    resources :abouts, only: [:index, :update]
    resources :socials, only: [:index, :create, :destroy]
    resources :abouts, only: [:index, :update]
  end
 
  resources :tags, only: :index
  get '/:slug', to: 'portfolios#show'
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :portfolio
  validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :portfolio
  has_one :additional_information, dependent: :delete

  enum kind: { profile: 1, about: 2, education: 3, experience: 4, hobby: 5, skill: 6,
               language: 7, social: 8, contact: 9, additional_information: 10, contact_form: 11 }

  enum side: { left: 1, right: 2 }, _suffix: true

  validates :side, presence: true
  validates :position, presence: true

  validates_with KindSideValidator
    
  validates :kind, presence: true, uniqueness: { scope: :portfolio_id }

  before_validation :set_position, on: :create, unless: -> { self.position.present? }


  private

    def set_position
      last_block_position = self.portfolio.blocks.where(side: self.side).maximum(:position)
      self.position = last_block_position ? last_block_position + 1 : 0
    end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :portfolio
 
  validates :phone, presence: true
  validates :email, presence: true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :portfolio
 
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :institution, presence: true
  validates_with DateIntervalValidator
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :portfolio
 
  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :company, presence: true
  validates_with DateIntervalValidator
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :portfolio
 
  validates :title, presence: true
  validates :percent, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :portfolio
 
  validates :title, presence: true
  validates :percent, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  MAX_NUMBER_OF_TAGS = 4
  paginates_per 5
 
  before_validation :set_slug, on: :create
 
  belongs_to :user
 
  has_one :profile, :dependent => :destroy
  has_one :about, :dependent => :destroy
 
  has_many :blocks, :dependent => :destroy
  has_many :portfolio_tags, :dependent => :destroy
  has_many :tags, through: :portfolio_tags
  has_many :educations, :dependent => :destroy
  has_many :experiences, :dependent => :destroy
  has_many :hobbies, :dependent => :destroy
  has_many :skills, :dependent => :destroy
  has_many :languages, :dependent => :destroy
  has_many :socials, :dependent => :destroy
  has_one :contact, :dependent => :destroy
  has_many :additional_informations, :dependent => :destroy
 
  validates :slug, presence: true, uniqueness: true
  validates :tags, length: { in: 0..MAX_NUMBER_OF_TAGS, message: "can't have more than #{MAX_NUMBER_OF_TAGS} tags" }
 
 
  enum temp_avatar: { blue_robot: 0, green_robot: 1, orange_red_robot: 2, purple_robot: 3, red_robot: 4, yellow_robot: 5 }
 
 
  before_create :set_random_temp_avatar
 
 
  private
 
 
  def set_random_temp_avatar
    avatars_list = Portfolio.temp_avatars.keys
    self.temp_avatar = avatars_list.sample
  end
 
  def set_slug
    if self.slug.nil?
      slug_generator = PortfolioSlugGeneratorService.new
      self.slug = slug_generator.call
    end
  end
 
end

app/models/portfolio_tag.rb
class PortfolioTag < ApplicationRecord
  belongs_to :portfolio
  belongs_to :tag
 
  validate :max_tags_for_portfolio
  validates :tag_id, uniqueness: { scope: :portfolio_id }
 
 
  private
 
 
  def max_tags_for_portfolio
    if portfolio.tags.count >= Portfolio::MAX_NUMBER_OF_TAGS
      errors.add(:portfolio, "can't have more than #{Portfolio::MAX_NUMBER_OF_TAGS} tags")
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :portfolio
 
  has_one_attached :photo
 
  validates :title, :name, presence: true
  validates :photo, file: { max_size_in_bytes: 3000, mime_types: [:jpg, :png] }

  def photo_url
    return "/avatars/#{self.portfolio.temp_avatar}.png" unless self.photo.attached?
    Rails.application.routes.url_helpers.rails_blob_path(self.photo, only_path: true)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :portfolio
 
  validates :title, presence: true
  validates :percent, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :portfolio
    
  enum kind: { facebook: 1, twitter: 2, linkedin: 3, github: 4, instagram: 5 }
  validates :kind, presence: true
  validates :url, presence: true, http_url: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :portfolio_tags
    validates :title, presence: true, uniqueness: true
  end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_many :portfolios, :dependent => :destroy


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :is_user_logged_in?
 
  def home
  end
 
  private
 
  def is_user_logged_in?
    if current_user
      redirect_to portfolios_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
 
  def index
    @portfolios = SearchPortfoliosService.call(search_params)
  end
 
  private
 
  def search_params
    params['page'] ||= 1
    params.permit(:tag, :place, :remote_ok, :page)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
      @tags = Tag.all.order(:title)
      render json: { tags: @tags }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def resource_name
      :user
    end
   
    def resource
      @resource ||= User.new
    end
   
    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
 
  def render_block(block)
    render partial: "portfolios/shared/#{block.kind}_widget.html.erb", locals: {portfolio: block.portfolio}
  end
 
  def render_profile_photo(portfolio)
    if portfolio.profile.present? && portfolio.profile.photo.attached?
      image_url = url_for(portfolio.profile.photo.variant(resize: "150x150"))
    end
    image_url ||= "avatars/#{portfolio.temp_avatar}.png"
    image_tag image_url,  class: 'responsive-img'
  end
 
 
  def render_profile_name(portfolio)
    return portfolio.profile.name if portfolio.profile.present?
    "Ainda não preenchido"
  end
 
 
  def render_profile_title(portfolio)
    return portfolio.profile.title if portfolio.profile.present?
    "Ainda não preenchido"
  end
 
 
  def render_portfolio_tags(tags)
    disabled_tags_quant = Portfolio::MAX_NUMBER_OF_TAGS - tags.count
    tags.each { |tag| concat draw_tag(tag.title) }
    disabled_tags_quant.times { concat draw_tag(unused_label, color: "grey") }
  end
 
 
  private
 
 
  def unused_label
    content_tag :i, "Vázia"
  end
 
 
  def draw_tag(title, color: "blue-grey")
    content_tag :div, class: "col s12 m6 l6" do
      concat content_tag :span, title, class: "label #{color} #{color}-darken-5 #{color}-text text-lighten-4"
    end
  end
end

app/views/search/_form.html.erb
<div class="row search-form">
  <div class="col l12 m12 s12">
    <div class="card-panel">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <div class="row">
          <div class="input-field col s12 m6 l3">
            <%= f.text_field :tag, placeholder: 'ruby, javascript, python...' %>
            <%= f.label "Habilidades", class: "font_20" %>
          </div>
 
          <div class="input-field col s12 m6 l4">
            <%= f.text_field :place, placeholder: 'São Paulo, Belo Horizonte, Recife...' %>
            <%= f.label "Local", class: "font_20" %>
          </div>
 
          <div class="input-field col s12 m6 l3">
            <label class="remote-ok">
              <%= f.check_box :remote_ok, class: "filled-in", value: false %>
              <span>Remote OK</span>
            </label>
          </div>
 
          <div class="input-field col s12 m6 l2">
            <%= f.button class: "btn right custom-green btn-large" do %>
              Buscar <i class="fa fa-icon fa-search right"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/search/_portfolio_result.html.erb
<div class="row portfolio-item">
  <div class="col l12 m12 s12">
    <%= link_to "/#{portfolio.slug}" do %>
      <div class="card-panel search-result hoverable">
        <div class="row">
          <div class="col l2 m6 s12 photo">
            <div class="row">
              <div class="col m10 offset-m1 s10 offset-s1 center">
                <%= render_profile_photo(portfolio) %>
              </div>
            </div>
          </div>
          <div class="col l4 m6 s12 profile">
            <p class="name custom-grey-text"><%= render_profile_name(portfolio) %></p>
            <p class="title custom-grey-text text-darken-1"><%= render_profile_title(portfolio) %></p>
          </div>
          
          <div class="col l3 m6 s12 place center">
            <% if portfolio.contact.present? %>
              <div>
                <i class="material-icons custom-blue-text small">place</i>
                <b class="custom-grey-text"><%= portfolio.contact.address_city %> - <%= portfolio.contact.address_country %></b>
              </div>
            <% end %>
          </div>
 
          <div class="col l2 m6 s12 center remote-ok">
            <div class="row">
              <% if portfolio.remote_ok? %>
                <p class="white-text custom-blue center">Remote OK</p>
              <% end %>
            </div>
          </div>
 
          <% if portfolio.featured? %>
            <div class="col l1 m1 hide-on-med-and-down trophy custom-grey darken-1 valign-wrapper">
              <div class="center"><i class="fa fa-icon fa-trophy fa-2x yellow-text"></i></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/search/index.html.erb
<div class="row">
  <div class="col m10 offset-m1 s12">
    <h5 class="grey-text page-title">Encontre os melhores desenvolvedores</h5>
 
    <%= render "form" %>
 
    <% @portfolios[:featured].each do |portfolio| %>
      <%= render "portfolio_result", portfolio: portfolio %>
    <% end %>
 
    <% @portfolios[:general].each do |portfolio| %>
      <%= render "portfolio_result", portfolio: portfolio %>
    <% end %>
 
    <div class="center">
      <%= paginate @portfolios[:general] %>
    </div>
  </div>
</div>